name: ⚡ CI

# Dependencies:
#   - SocketDev/socket-registry/.github/workflows/ci.yml

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Run CI Pipeline
    uses: SocketDev/socket-registry/.github/workflows/ci.yml@27eee5cbe49334ac7e0e2f69dcdfdd501300e04f # main (2026-05-15)